{% set name = "godoctor" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/godoctor/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c1517a444783224fdad46b7a7ce82407b714b121f60b17e9df9834b5b6773332

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - m2-grep  # [win]
  commands:
    - {{ name }} --help 2>&1 | grep -q "Go source code refactoring tool"

about:
  home: https://github.com/godoctor/{{ name }}
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Go Doctor - The Golang Refactoring Engine
  dev_url: https://github.com/godoctor/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
